/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gmo.rpt;

/**

 @author kevin leandro
 */
public class RptCampania extends javax.swing.JInternalFrame {

    /**
     Creates new form RptCampania
     */
    public RptCampania() {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cardChart = new kevin.component.panel.Panel();
        cardChart1 = new kevin.component.panel.Panel();
        cardChart2 = new kevin.component.panel.Panel();
        cardChart3 = new kevin.component.panel.Panel();
        toolbar1 = new kevin.component.toolbar.Toolbar();
        gMOMenuBar1 = new kevin.component.menu.GMOMenuBar();
        jMenu2 = new javax.swing.JMenu();
        gMOMenuItemRadio1 = new kevin.component.menu.GMOMenuItemRadio();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reporte General de Camapaña");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardChartLayout = new javax.swing.GroupLayout(cardChart);
        cardChart.setLayout(cardChartLayout);
        cardChartLayout.setHorizontalGroup(
            cardChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        cardChartLayout.setVerticalGroup(
            cardChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jPanel1.add(cardChart, "card2");

        javax.swing.GroupLayout cardChart1Layout = new javax.swing.GroupLayout(cardChart1);
        cardChart1.setLayout(cardChart1Layout);
        cardChart1Layout.setHorizontalGroup(
            cardChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        cardChart1Layout.setVerticalGroup(
            cardChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jPanel1.add(cardChart1, "card2");

        javax.swing.GroupLayout cardChart2Layout = new javax.swing.GroupLayout(cardChart2);
        cardChart2.setLayout(cardChart2Layout);
        cardChart2Layout.setHorizontalGroup(
            cardChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        cardChart2Layout.setVerticalGroup(
            cardChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jPanel1.add(cardChart2, "card2");

        javax.swing.GroupLayout cardChart3Layout = new javax.swing.GroupLayout(cardChart3);
        cardChart3.setLayout(cardChart3Layout);
        cardChart3Layout.setHorizontalGroup(
            cardChart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        cardChart3Layout.setVerticalGroup(
            cardChart3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        jPanel1.add(cardChart3, "card2");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        toolbar1.setBackground(new java.awt.Color(255, 255, 255));
        toolbar1.setCHART(true);
        toolbar1.setDATA(true);
        toolbar1.setEXCEL(true);
        toolbar1.setRECARGAR(true);
        toolbar1.setOpaque(true);
        getContentPane().add(toolbar1, java.awt.BorderLayout.WEST);

        jMenu2.setText("Configuracion");

        gMOMenuItemRadio1.setSelected(true);
        gMOMenuItemRadio1.setText("gMOMenuItemRadio1");
        jMenu2.add(gMOMenuItemRadio1);

        gMOMenuBar1.add(jMenu2);

        setJMenuBar(gMOMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private kevin.component.panel.Panel cardChart;
    private kevin.component.panel.Panel cardChart1;
    private kevin.component.panel.Panel cardChart2;
    private kevin.component.panel.Panel cardChart3;
    private kevin.component.menu.GMOMenuBar gMOMenuBar1;
    private kevin.component.menu.GMOMenuItemRadio gMOMenuItemRadio1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private kevin.component.toolbar.Toolbar toolbar1;
    // End of variables declaration//GEN-END:variables
}
