/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gmo.internal;

import java.awt.Window;

/**

 @author Miguel
 */
public class AdminMotivos extends javax.swing.JInternalFrame {

    Window Frame;

    public AdminMotivos(Window frame) {
        initComponents();
        this.Frame = frame;
    }

    /**
     This method is called from within the constructor to initialize the form.
     WARNING: Do NOT modify this code. The content of this method is always
     regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contenedor = new javax.swing.JPanel();
        panelData = new javax.swing.JPanel();
        jScrollPane = new javax.swing.JScrollPane();
        tabla3 = new kevin.component.tabla.TablaSmart();
        panelNuevoEditar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        edtIdMotivo = new kevin.component.edittext.EditText();
        edtNombreCorto = new kevin.component.edittext.EditText();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        edtObservaciones = new kevin.component.textarea.TextArea();
        jPanel2 = new javax.swing.JPanel();
        chkCntrEstados = new kevin.component.checkbox.CheckBox();
        chkProgramacion = new kevin.component.checkbox.CheckBox();
        chkMaquinaria = new kevin.component.checkbox.CheckBox();
        chkCosecha = new kevin.component.checkbox.CheckBox();
        chkCostos = new kevin.component.checkbox.CheckBox();
        chkRecepcion = new kevin.component.checkbox.CheckBox();
        chkRiego = new kevin.component.checkbox.CheckBox();
        chkCntProceso = new kevin.component.checkbox.CheckBox();
        chkAlerta = new kevin.component.checkbox.CheckBox();
        chkFSanidad = new kevin.component.checkbox.CheckBox();
        chkTareo = new kevin.component.checkbox.CheckBox();
        chkAviso = new kevin.component.checkbox.CheckBox();
        chkAsisPerson = new kevin.component.checkbox.CheckBox();
        chkAsisTransp = new kevin.component.checkbox.CheckBox();
        chkDespacho = new kevin.component.checkbox.CheckBox();
        chkActivo = new kevin.component.checkbox.CheckBox();
        chkPreTareo = new kevin.component.checkbox.CheckBox();
        chkCtrlBoletas = new kevin.component.checkbox.CheckBox();
        edtDescripcionn = new kevin.component.edittext.EditText();
        panelImportar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaImport = new kevin.component.tabla.TablaSmart();
        toolbar1 = new kevin.component.toolbar.Toolbar();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(true);
        setTitle("Administracion de Motivos GMO");

        contenedor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor.setLayout(new java.awt.CardLayout());

        panelData.setOpaque(false);

        tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla3.setColumnSelectionAllowed(true);
        jScrollPane.setViewportView(tabla3);

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );

        contenedor.add(panelData, "cardGeneral");

        panelNuevoEditar.setOpaque(false);
        panelNuevoEditar.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        edtIdMotivo.setDigit_limit(11);
        edtIdMotivo.setLabel("ID Motivo");
        edtIdMotivo.setModo(kevin.component.edittext.EditText.MODO.NUMEROS_CANTIDAD);
        edtIdMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtIdMotivoActionPerformed(evt);
            }
        });

        edtNombreCorto.setDigit_limit(11);
        edtNombreCorto.setLabel("Nombre Corto");
        edtNombreCorto.setModo(kevin.component.edittext.EditText.MODO.NORMAL);
        edtNombreCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNombreCortoActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Observaciones:");

        jScrollPane4.setViewportView(edtObservaciones);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        chkCntrEstados.setText("Control de Estados");
        chkCntrEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCntrEstadosActionPerformed(evt);
            }
        });
        jPanel2.add(chkCntrEstados);

        chkProgramacion.setText("Programacion");
        chkProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProgramacionActionPerformed(evt);
            }
        });
        jPanel2.add(chkProgramacion);

        chkMaquinaria.setText("Maquinaria");
        chkMaquinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMaquinariaActionPerformed(evt);
            }
        });
        jPanel2.add(chkMaquinaria);

        chkCosecha.setText("Cosecha");
        chkCosecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCosechaActionPerformed(evt);
            }
        });
        jPanel2.add(chkCosecha);

        chkCostos.setText("Costos");
        chkCostos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCostosActionPerformed(evt);
            }
        });
        jPanel2.add(chkCostos);

        chkRecepcion.setText("Recepcion");
        chkRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRecepcionActionPerformed(evt);
            }
        });
        jPanel2.add(chkRecepcion);

        chkRiego.setText("Riego");
        chkRiego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRiegoActionPerformed(evt);
            }
        });
        jPanel2.add(chkRiego);

        chkCntProceso.setText("Control de Procesos");
        chkCntProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCntProcesoActionPerformed(evt);
            }
        });
        jPanel2.add(chkCntProceso);

        chkAlerta.setText("Alerta");
        chkAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlertaActionPerformed(evt);
            }
        });
        jPanel2.add(chkAlerta);

        chkFSanidad.setText("FitoSanidad");
        chkFSanidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFSanidadActionPerformed(evt);
            }
        });
        jPanel2.add(chkFSanidad);

        chkTareo.setSelected(true);
        chkTareo.setText("Tareo");
        chkTareo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTareoActionPerformed(evt);
            }
        });
        jPanel2.add(chkTareo);

        chkAviso.setText("Aviso");
        chkAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAvisoActionPerformed(evt);
            }
        });
        jPanel2.add(chkAviso);

        chkAsisPerson.setText("Asis Personal");
        chkAsisPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAsisPersonActionPerformed(evt);
            }
        });
        jPanel2.add(chkAsisPerson);

        chkAsisTransp.setText("Asis Transportistas");
        chkAsisTransp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAsisTranspActionPerformed(evt);
            }
        });
        jPanel2.add(chkAsisTransp);

        chkDespacho.setText("Despacho");
        chkDespacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDespachoActionPerformed(evt);
            }
        });
        jPanel2.add(chkDespacho);

        chkActivo.setSelected(true);
        chkActivo.setText("Activo");
        chkActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActivoActionPerformed(evt);
            }
        });
        jPanel2.add(chkActivo);

        chkPreTareo.setText("PreTareo");
        chkPreTareo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPreTareoActionPerformed(evt);
            }
        });
        jPanel2.add(chkPreTareo);

        chkCtrlBoletas.setText("Control de Boletas");
        chkCtrlBoletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCtrlBoletasActionPerformed(evt);
            }
        });
        jPanel2.add(chkCtrlBoletas);

        edtDescripcionn.setDigit_limit(11);
        edtDescripcionn.setLabel("Descripcion");
        edtDescripcionn.setModo(kevin.component.edittext.EditText.MODO.NORMAL);
        edtDescripcionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtDescripcionnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(edtDescripcionn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(edtIdMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(edtNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtIdMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtDescripcionn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 255, 10);
        panelNuevoEditar.add(jPanel1, gridBagConstraints);

        contenedor.add(panelNuevoEditar, "cardFilter");

        panelImportar.setOpaque(false);

        tablaImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaImport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jScrollPane2.setViewportView(tablaImport);

        javax.swing.GroupLayout panelImportarLayout = new javax.swing.GroupLayout(panelImportar);
        panelImportar.setLayout(panelImportarLayout);
        panelImportarLayout.setHorizontalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImportarLayout.setVerticalGroup(
            panelImportarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImportarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        contenedor.add(panelImportar, "cardImportar");

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        toolbar1.setBackground(new java.awt.Color(255, 255, 255));
        toolbar1.setAGREGAR(true);
        toolbar1.setANULAR(true);
        toolbar1.setEDITAR(true);
        toolbar1.setELIMINAR(true);
        toolbar1.setENVIAR(false);
        toolbar1.setEXCEL(false);
        toolbar1.setFILTRAR(false);
        toolbar1.setGUARDAR(false);
        toolbar1.setHISTORIAL(false);
        toolbar1.setIMPORTAR(false);
        toolbar1.setIMPRIMIR(false);
        toolbar1.setINDICADOR(false);
        toolbar1.setIREPORT(false);
        toolbar1.setRECARGAR(true);
        toolbar1.setOpaque(true);
        getContentPane().add(toolbar1, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTareoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTareoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTareoActionPerformed

    private void edtIdMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtIdMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtIdMotivoActionPerformed

    private void chkCntProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCntProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCntProcesoActionPerformed

    private void chkRiegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRiegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRiegoActionPerformed

    private void chkRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRecepcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkRecepcionActionPerformed

    private void chkCosechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCosechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCosechaActionPerformed

    private void chkProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProgramacionActionPerformed

    private void chkPreTareoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPreTareoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPreTareoActionPerformed

    private void chkDespachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDespachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDespachoActionPerformed

    private void chkAsisPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAsisPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAsisPersonActionPerformed

    private void chkAsisTranspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAsisTranspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAsisTranspActionPerformed

    private void chkAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAvisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAvisoActionPerformed

    private void chkFSanidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFSanidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFSanidadActionPerformed

    private void chkAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAlertaActionPerformed

    private void chkActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkActivoActionPerformed

    private void chkCntrEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCntrEstadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCntrEstadosActionPerformed

    private void chkMaquinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMaquinariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMaquinariaActionPerformed

    private void chkCostosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCostosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCostosActionPerformed

    private void edtNombreCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNombreCortoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNombreCortoActionPerformed

    private void edtDescripcionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtDescripcionnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtDescripcionnActionPerformed

    private void chkCtrlBoletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCtrlBoletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCtrlBoletasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private kevin.component.checkbox.CheckBox chkActivo;
    private kevin.component.checkbox.CheckBox chkAlerta;
    private kevin.component.checkbox.CheckBox chkAsisPerson;
    private kevin.component.checkbox.CheckBox chkAsisTransp;
    private kevin.component.checkbox.CheckBox chkAviso;
    private kevin.component.checkbox.CheckBox chkCntProceso;
    private kevin.component.checkbox.CheckBox chkCntrEstados;
    private kevin.component.checkbox.CheckBox chkCosecha;
    private kevin.component.checkbox.CheckBox chkCostos;
    private kevin.component.checkbox.CheckBox chkCtrlBoletas;
    private kevin.component.checkbox.CheckBox chkDespacho;
    private kevin.component.checkbox.CheckBox chkFSanidad;
    private kevin.component.checkbox.CheckBox chkMaquinaria;
    private kevin.component.checkbox.CheckBox chkPreTareo;
    private kevin.component.checkbox.CheckBox chkProgramacion;
    private kevin.component.checkbox.CheckBox chkRecepcion;
    private kevin.component.checkbox.CheckBox chkRiego;
    private kevin.component.checkbox.CheckBox chkTareo;
    private javax.swing.JPanel contenedor;
    private kevin.component.edittext.EditText edtDescripcionn;
    private kevin.component.edittext.EditText edtIdMotivo;
    private kevin.component.edittext.EditText edtNombreCorto;
    private kevin.component.textarea.TextArea edtObservaciones;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelImportar;
    private javax.swing.JPanel panelNuevoEditar;
    private kevin.component.tabla.TablaSmart tabla3;
    private kevin.component.tabla.TablaSmart tablaImport;
    private kevin.component.toolbar.Toolbar toolbar1;
    // End of variables declaration//GEN-END:variables
}
